### PR TITLE
issue/103 Bugfix wrong syntax

### LINKED ISSUE #103: The xapiwrapper config can't be changed
There is an issue on the setWrapperConfig function on XAPI that does not allow change the xapiwrapper config.
It seems to me that the problem lies [in this line](https://github.com/adaptlearning/adapt-contrib-xapi/blob/master/js/XAPI.js#L329)

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #103 

### Fixed
* Checked no keys rather than no length

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Comment by oliverfoster** [comment]
It doesn't look as though we'll get any more +1s on this. Happy to merge? @cahirodoherty-learningpool @lc-alexanderbenesch ?

**Comment by oliverfoster** [comment]
It doesn't look as though we'll get any more +1s on this. Happy to merge? @cahirodoherty-learningpool @lc-alexanderbenesch ?

**Review by ethan-lp — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Pull request merged**
